### ISSUE TITLE
Expectable sequence of SSAP columns

### ISSUE THREAD

**Issue by msdemlei** [SPLAT-VO/starjava#2]
In the SSAP responses, the column order is determined by what the
services use in their VOTables.  This is often somewhat arbitrary and,
worse, varies from service to service.  I'd much rather see a
predictable order for the core SSA columns (as identified by utypes).

Here's a proposal for the sequence that I think would satisfy the
typical user's needs best (but perhaps feedback is necessary to figure
out what's really best; not sure if I'd like to make this configurable):

```
ssa:Char.SpectralAxis.Coverage.Bounds.Start
ssa:Char.SpectralAxis.Coverage.Bounds.Stop
ssa:DataID.Title
ssa:Target.Name
ssa:Char.TimeAxis.Coverage.Location.Value
ssa:Char.TimeAxis.Coverage.Bounds.Extent
ssa:Derived.SNR
ssa:Dataset.Length
ssa:Access.Reference
ssa:Access.Format
ssa:Access.Size
(other columns in the order given by the service)
```

Ideally, if a corresponding column is missing, an empty column will be displayed,
except if there's a PARAM for this utype, in which case the associated
value would be displayed in all cells.

**Comment by mmpcn** [comment]
Actually, the table columns are already sorted, by following utypes/order:
   "query.score", 
    "target.name", 
     "char.spatialaxis.coverage.location.value",                    
     "char.spectralaxis.coverage.bounds.start",
      "char.spectralaxis.coverage.bounds.stop",  
      "char.spatialaxis.coverage.bounds.extent", 
      "char.timeaxis.coverage.bounds.start", 
      "char.timeaxis.coverage.bounds.stop", 
       "access.format" 

If these utypes are missing, no empty column are created. 
I can change it to the utypes/order suggested. I'm not sure about the empty column, have to
think about that.

**Comment by msdemlei** [comment]
Ah, sorry -- I hadn't noticed you were already re-ordering things.

Anyway, query.score is probably fairly meaningless for most services, so I'd definitely push it back quite a bit.  And given that the user presumably has already looked for an object and that's probably a fairly constant piece of information, I'd push back target.name and the spatial location at least behind the spectal bounds.  Finally, as Aladin uses the title as a very prominant artefact in discovery, I'd like to see this available here, too, in order to have some basic consistency among VO clients.

**Comment by mmpcn** [comment]
I have changed to the sequence you suggested.
If the spectralaxis start and stop columns are not available, but value and extent are, these will be used.
