### ISSUE TITLE
SAMP icon

### ISSUE THREAD

**Issue by msdemlei** [SPLAT-VO/starjava#23]
SPLAT's SAMP icon (the one with the green/red circle) is not very pretty and, worse, is different from what TOPCAT has for the same purpose.  I'd say the two programs should use the same icon for their SAMP windows for consistency, and since TOPCAT's is prettier, we should use that.

**Comment by mmpcn** [comment]
Now Topcat's icon is used. 
The old SPLAT icon changed colours to indicate that SAMP is connected/disconnected.
So I changed the icon to show a small green dot in the middle when it's connected.
