### ISSUE TITLE
Obscore window simple query interface changes

### ISSUE THREAD

**Issue by petrskoda** [SPLAT-VO/starjava#29]
The simple query window (not the ADQL but the conesearch like) is just copy of SSA - so it does not reflect differences in obscore - needs more selectors - e.g. dataproduct type, calib level , 
This needs to be redesigned after making review of solutions planned in other VO tools

**Comment by petrskoda** [comment]
The dataproduct type is now hardcoded for spectra so it prevents all other types to be accessed. So the absolute priority is at least add button which allows to select the all data product types according to IVOA standard of obscore  with spectra as a default position on spinner. But it make sense use SPLAT obscore even for finding images or catalogues (but mainly timeseries) as the table may be send by SAMP to Aladin or TOPCAT - its users's responsibility what to do next. Suppose we have image - 2D spectrum - raw and we have datalink operations for combining all rows to yield 1D spectrum which may be displayed . In future even other general data cube operations .

**Comment by and146** [comment]
Test version of data product type selector added to builds 35 and 36 (splat-ond branch).
