### ISSUE TITLE
Non standard characters

### ISSUE THREAD

**Issue by ignacionegueruela** [SPLAT-VO/starjava#3]
I am trying to use the new version of splat-vo, but the programme is unable to work every time it meets a directory that contains a file whose name has a non-standard character (i.e., anything like ó or ö). It will just give an error, not list the contents of the directory and hang there.

**Comment by mmpcn** [comment]
This will be corrected in the new release. To correct your current version, please apply this change to starjava/splat/src/script/splat:
[scriptdiff.txt](https://github.com/user-attachments/files/16097637/scriptdiff.txt)

**Comment by mmpcn** [comment]
This will be fixed in the next release.
To fix your current version, make this changes in the file 
<your splat installation dir>/bin/splat/splat:
[scriptdiff.txt](https://github.com/user-attachments/files/16097774/scriptdiff.txt)
