### ISSUE TITLE
obscore and ssa windows identical UX

### ISSUE THREAD

**Issue by petrskoda** [SPLAT-VO/starjava#30]
The SSA and obscore windows should have the same behaviour

saving services to local XML file, read from it after start and when registry call returnes new services that it should merge them . But at the same time the services in memory should allow not only adding serixce but also removing service and this should be remembered automatically. During restart this list is read and no registry is called automatically until requested

**Comment by petrskoda** [comment]
please comment if youre not convinced - main reason - fine-grain selection of services, eliminating those not responding in case of all-VO discovery query, running demos in case of weak or no connectivity - using local server on laptop (manually added - temporary)

**Comment by mmpcn** [comment]
I agree that it should be the same. It is intended to make ssap and obscore server and spectra selection use the same gui, as far as possible.

**Comment by mmpcn** [comment]
After refactoring, it should work now (commit 3ae8d7ee4ff62365ef7fb3f2666245f5024268ad)
